name: InfluxBro
description: >-
  Browse InfluxDB (table + mini graph), configure in UI, entity_id/friendly_name
  filters, and optionally delete ranges
version: "1.12.388"
slug: influxbro
url: "https://github.com/thomas682/HA-Addons/tree/main/influxbro"

arch:
  - amd64
  - aarch64
  - armv7
  - armhf

startup: services
boot: auto

ports:
  8099/tcp: null

ports_description:
  8099/tcp: "Optional (Dev/Tests): Host-Port fuer direkten Zugriff ohne Ingress. Standard: deaktiviert."

ingress: true
ingress_port: 8099

hassio_api: true
homeassistant_api: true
supervisor_api: true

hassio_role: manager

panel_icon: "mdi:database-eye"
panel_title: "InfluxBro"
map:
  - config:rw
