name: InfluxBro by Thomae
description: Browse and delete measures from InfluxDB data
version: "1.1.1"
slug: influxbro
url: "http://192.168.2.65:7070/thomas/ha_addons/influxbro"

arch:
  - amd64
  - aarch64
  - armv7
  - armhf

startup: services
boot: auto

ports:
  8099/tcp: 8099

options:
  autodetect_path: "/homeassistant/influx.yaml"

schema:
  autodetect_path: str